"""phase1_v10_base_tables

Revision ID: 3760e227ac2a
Revises:
Create Date: 2026-05-16 03:37:58.109006+00:00
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3760e227ac2a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("name_zh", sa.String(length=200), nullable=True),
        sa.Column("name_en", sa.String(length=200), nullable=True),
        sa.Column("hk_stock_code", sa.String(length=10), nullable=True),
        sa.Column("a_share_code", sa.String(length=10), nullable=True),
        sa.Column("us_adr_code", sa.String(length=10), nullable=True),
        sa.Column("industry_code", sa.String(length=20), nullable=True),
        sa.Column("incorporation_country", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_table(
        "comparable_companies",
        sa.Column("ticker", sa.String(length=30), nullable=False),
        sa.Column("market", sa.String(length=10), nullable=True),
        sa.Column("company_name", sa.String(length=200), nullable=True),
        sa.Column("industry_code", sa.String(length=20), nullable=True),
        sa.Column("sub_industry", sa.String(length=100), nullable=True),
        sa.Column("market_cap_usd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("enterprise_value_usd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("ps_ttm", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("pe_ttm", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ev_sales_ttm", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ev_ebitda_ttm", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("adjustments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("snapshot_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comparable_companies")),
    )
    op.create_table(
        "cornerstone_investors",
        sa.Column("name_zh", sa.String(length=200), nullable=True),
        sa.Column("name_en", sa.String(length=200), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("parent_org", sa.String(length=200), nullable=True),
        sa.Column("ultimate_holder", sa.String(length=200), nullable=True),
        sa.Column("home_country", sa.String(length=50), nullable=True),
        sa.Column("signal_strength_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("extra_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cornerstone_investors")),
    )
    op.create_table(
        "ipo_events",
        sa.Column("stock_code", sa.String(length=10), nullable=True),
        sa.Column("company_name_zh", sa.String(length=200), nullable=True),
        sa.Column("company_name_en", sa.String(length=200), nullable=True),
        sa.Column("listing_type", sa.String(length=20), nullable=True),
        sa.Column("industry_code", sa.String(length=20), nullable=True),
        sa.Column("sponsor_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("a1_filing_date", sa.Date(), nullable=True),
        sa.Column("hearing_date", sa.Date(), nullable=True),
        sa.Column("pricing_date", sa.Date(), nullable=True),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("issue_size_hkd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("use_of_proceeds", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("regulatory_regime", sa.String(length=30), nullable=True),
        sa.Column("is_18c_pre_commercial", sa.Boolean(), nullable=True),
        sa.Column("ah_pair_a_code", sa.String(length=10), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ipo_events")),
    )
    op.create_table(
        "sponsors",
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("is_sfc_licensed", sa.Boolean(), nullable=True),
        sa.Column("track_record_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("cases_count_24m", sa.Integer(), nullable=True),
        sa.Column("avg_day1_return", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("avg_6m_return", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sponsors")),
    )
    op.create_table(
        "cornerstone_investments",
        sa.Column("ipo_id", sa.UUID(), nullable=False),
        sa.Column("investor_id", sa.UUID(), nullable=False),
        sa.Column("commitment_amount_hkd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("pct_of_offering", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("lockup_months", sa.Integer(), nullable=True),
        sa.Column("disclosure_date", sa.Date(), nullable=True),
        sa.Column("is_anchor", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investor_id"],
            ["cornerstone_investors.id"],
            name=op.f("fk_cornerstone_investments_investor_id_cornerstone_investors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ipo_id"],
            ["ipo_events.id"],
            name=op.f("fk_cornerstone_investments_ipo_id_ipo_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cornerstone_investments")),
    )
    op.create_index(
        "ix_cornerstone_investments_ipo_investor",
        "cornerstone_investments",
        ["ipo_id", "investor_id"],
        unique=False,
    )
    op.create_table(
        "financial_snapshots",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("fiscal_period", sa.String(length=8), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=True),
        sa.Column("revenue_rmb", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("gross_profit_rmb", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("gross_margin", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("rd_expense_rmb", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("rd_pct_of_revenue", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("net_profit_rmb", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("adjusted_net_profit_rmb", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("operating_cash_flow_rmb", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("cash_balance_rmb", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_financial_snapshots_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_snapshots")),
    )
    op.create_index(
        "ix_financial_snapshots_company_period",
        "financial_snapshots",
        ["company_id", "fiscal_year", "fiscal_period"],
        unique=True,
    )
    op.create_table(
        "ipo_allocations",
        sa.Column("ipo_id", sa.UUID(), nullable=False),
        sa.Column("tranche", sa.String(length=30), nullable=False),
        sa.Column("allocation_amount_hkd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("allocation_pct_of_offering", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("investor_count", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ipo_id"],
            ["ipo_events.id"],
            name=op.f("fk_ipo_allocations_ipo_id_ipo_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ipo_allocations")),
    )
    op.create_index(
        "ix_ipo_allocations_ipo_tranche", "ipo_allocations", ["ipo_id", "tranche"], unique=False
    )
    op.create_table(
        "ipo_postmarket",
        sa.Column("ipo_id", sa.UUID(), nullable=False),
        sa.Column("day1_return", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("day5_return", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("day22_return", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("day126_return", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("day127_return", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("day252_return", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("max_drawdown_d126", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("cornerstone_held_after_lockup", sa.Boolean(), nullable=True),
        sa.Column("returns_by_day", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "cornerstone_held_pct_by_day", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ipo_id"],
            ["ipo_events.id"],
            name=op.f("fk_ipo_postmarket_ipo_id_ipo_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ipo_postmarket")),
        sa.UniqueConstraint("ipo_id", name=op.f("uq_ipo_postmarket_ipo_id")),
    )
    op.create_table(
        "ipo_pricings",
        sa.Column("ipo_id", sa.UUID(), nullable=False),
        sa.Column("price_range_low", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("price_range_high", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("final_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("intl_oversubscription", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("retail_oversubscription", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("margin_subscription_multiple", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("allocation_mechanism", sa.String(length=10), nullable=True),
        sa.Column("final_public_allocation_pct", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ipo_id"],
            ["ipo_events.id"],
            name=op.f("fk_ipo_pricings_ipo_id_ipo_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ipo_pricings")),
        sa.UniqueConstraint("ipo_id", name=op.f("uq_ipo_pricings_ipo_id")),
    )
    op.create_table(
        "prospectus_docs",
        sa.Column("ipo_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=True),
        sa.Column("filing_date", sa.Date(), nullable=True),
        sa.Column("pdf_path", sa.String(length=500), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ipo_id"],
            ["ipo_events.id"],
            name=op.f("fk_prospectus_docs_ipo_id_ipo_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospectus_docs")),
    )
    op.create_table(
        "prospectus_extractions",
        sa.Column("prospectus_id", sa.UUID(), nullable=False),
        sa.Column("extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("extraction_version", sa.String(length=20), nullable=True),
        sa.Column("needs_human_review", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prospectus_id"],
            ["prospectus_docs.id"],
            name=op.f("fk_prospectus_extractions_prospectus_id_prospectus_docs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospectus_extractions")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prospectus_extractions")
    op.drop_table("prospectus_docs")
    op.drop_table("ipo_pricings")
    op.drop_table("ipo_postmarket")
    op.drop_index("ix_ipo_allocations_ipo_tranche", table_name="ipo_allocations")
    op.drop_table("ipo_allocations")
    op.drop_index("ix_financial_snapshots_company_period", table_name="financial_snapshots")
    op.drop_table("financial_snapshots")
    op.drop_index("ix_cornerstone_investments_ipo_investor", table_name="cornerstone_investments")
    op.drop_table("cornerstone_investments")
    op.drop_table("sponsors")
    op.drop_table("ipo_events")
    op.drop_table("cornerstone_investors")
    op.drop_table("comparable_companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
