"""phase2_widen_cornerstone_strings

Revision ID: 7efd3de0efa7
Revises: e82407eae19a
Create Date: 2026-05-16 04:17:03.713460+00:00
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7efd3de0efa7"
down_revision: str | None = "e82407eae19a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cornerstone_investors",
        "name_zh",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "cornerstone_investors",
        "name_en",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "cornerstone_investors",
        "parent_org",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=300),
        existing_nullable=True,
    )
    op.alter_column(
        "cornerstone_investors",
        "ultimate_holder",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=300),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cornerstone_investors",
        "ultimate_holder",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "cornerstone_investors",
        "parent_org",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "cornerstone_investors",
        "name_en",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "cornerstone_investors",
        "name_zh",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
