"""phase2_widen_industry_code

Revision ID: e82407eae19a
Revises: 3760e227ac2a
Create Date: 2026-05-16 04:15:58.182789+00:00
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e82407eae19a"
down_revision: str | None = "3760e227ac2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "companies",
        "industry_code",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=120),
        existing_nullable=True,
    )
    op.alter_column(
        "comparable_companies",
        "industry_code",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=120),
        existing_nullable=True,
    )
    op.alter_column(
        "ipo_events",
        "industry_code",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=120),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ipo_events",
        "industry_code",
        existing_type=sa.String(length=120),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "comparable_companies",
        "industry_code",
        existing_type=sa.String(length=120),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "companies",
        "industry_code",
        existing_type=sa.String(length=120),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
